INFINITE_LABELS:
  - "x" # x - infinite dimensional space
  - "u" # u - infinite dimensional space
  - "d" # d - infinite dimensional space
  - "r" # r - infinite dimensional space
FINITE_LABELS:
  - "z" # z - space where A_n lives  | 2d
  - "q" # q - the space of the side leg of Q  |  8d
  - "g" # g - the wiggly space of T | 16d
  - "z'" # z' - the part of zâŠ—z that will go to the infinite dimensional sectors  | 2d
  - "t" # t - section of the auxiliary space | 1d
  - "w" # w - section of the auxiliary space | 3d
  - "c" # c - section of the auxiliary space | 1d
  

