name = "TensorDiagrams"
uuid = "e7e750ee-38be-443c-97a0-aa081d444d92"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"


[targets]
test = ["Aqua", "Test", "BenchmarkTools"]
