name = "TensorDiagrams"
uuid = "e7e750ee-38be-443c-97a0-aa081d444d92"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
